import SwiftSyntaxMacros
import SwiftSyntaxMacrosTestSupport
import XCTest

@testable import CamperMacros

final class AutoMockableTests: XCTestCase {
    let testMacros: [String: Macro.Type] = [
        "AutoMockable": AutoMockable.self,
        "MockName": MockName.self,
    ]

    func testMockNameOverridesGeneratedPrefix() {
        assertMacroExpansion(
            """
            @AutoMockable
            protocol Service {
                @MockName("track")
                func track(event: String, properties: [String: String])
            }
            """,
            expandedSource: """
            protocol Service {
                func track(event: String, properties: [String: String])
            }

            class ServiceMock: Service, @unchecked Sendable {

                init() {
                }

                //MARK: - track
                var trackCallsCount = 0
                var trackCalled: Bool {
                    return trackCallsCount > 0
                }
                var trackReceivedArguments: (event: String, properties: [String: String])?
                var trackReceivedInvocations: [(event: String, properties: [String: String])] = []
                var trackClosure: ((String, [String: String]) -> ())?
                func track(event: String, properties: [String: String]) {
                    trackCallsCount += 1
                    trackReceivedArguments = (event: event, properties: properties)
                    trackReceivedInvocations.append((event: event, properties: properties))
                    trackClosure?(event, properties)
                }
            }
            """,
            macros: testMacros
        )
    }

    func testWithoutMockNameUsesAutoGeneratedPrefix() {
        assertMacroExpansion(
            """
            @AutoMockable
            protocol Service {
                func track(event: String, properties: [String: String])
            }
            """,
            expandedSource: """
            protocol Service {
                func track(event: String, properties: [String: String])
            }

            class ServiceMock: Service, @unchecked Sendable {

                init() {
                }

                //MARK: - track
                var trackEventStringPropertiesStringStringCallsCount = 0
                var trackEventStringPropertiesStringStringCalled: Bool {
                    return trackEventStringPropertiesStringStringCallsCount > 0
                }
                var trackEventStringPropertiesStringStringReceivedArguments: (event: String, properties: [String: String])?
                var trackEventStringPropertiesStringStringReceivedInvocations: [(event: String, properties: [String: String])] = []
                var trackEventStringPropertiesStringStringClosure: ((String, [String: String]) -> ())?
                func track(event: String, properties: [String: String]) {
                    trackEventStringPropertiesStringStringCallsCount += 1
                    trackEventStringPropertiesStringStringReceivedArguments = (event: event, properties: properties)
                    trackEventStringPropertiesStringStringReceivedInvocations.append((event: event, properties: properties))
                    trackEventStringPropertiesStringStringClosure?(event, properties)
                }
            }
            """,
            macros: testMacros
        )
    }

    func testArrayParameterStillGetsPluralSuffix() {
        // Regression guard: [T] gets `s` suffix, [K: V] does not.
        assertMacroExpansion(
            """
            @AutoMockable
            protocol Service {
                func observe(values: [String])
            }
            """,
            expandedSource: """
            protocol Service {
                func observe(values: [String])
            }

            class ServiceMock: Service, @unchecked Sendable {

                init() {
                }

                //MARK: - observe
                var observeValuesStringsCallsCount = 0
                var observeValuesStringsCalled: Bool {
                    return observeValuesStringsCallsCount > 0
                }
                var observeValuesStringsReceivedValues: [String]?
                var observeValuesStringsReceivedInvocations: [[String]] = []
                var observeValuesStringsClosure: (([String]) -> ())?
                func observe(values: [String]) {
                    observeValuesStringsCallsCount += 1
                    observeValuesStringsReceivedValues = values
                    observeValuesStringsReceivedInvocations.append(values)
                    observeValuesStringsClosure?(values)
                }
            }
            """,
            macros: testMacros
        )
    }
}
